site:
  base_url: http://d3-geomap.github.io
  disqus_shortname: null

indexes:
- path: tags
  var: tags

templates:
- content_type: index
  template: index.html
- content_type: doc
  template: post.html
